# Generated by Django 5.0.1 on 2024-01-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0004_remove_avto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='karobka',
            field=models.CharField(choices=[('Mexanika', 'Mexanika'), ('Avtomat', 'Avtomat'), ('Tiptronik', 'Tiptronik'), ('Variator', 'Variator'), ('Robot', 'Robot')], max_length=50, verbose_name='Karobka'),
        ),
        migrations.AlterField(
            model_name='avto',
            name='rang',
            field=models.CharField(choices=[('Oq', 'Oq'), ('Qaymoq rang', 'Qaymoq rang'), ('Delfin', 'Delfin'), ('Mokriy asfalt', 'Mokriy asfalt'), ('Qora', 'Qora'), ('Kumush rang', 'Kumush rang'), ('Saxara (qum rang)', 'Saxara (qum rang)'), ('Sadaf-jigarrang', 'Sadaf-jigarrang'), ('Sariq-yashil rang', 'Sariq-yashil rang'), ("Ko'k xavorang", "Ko'k xavorang"), ('Olcha', 'Olcha'), ("K'k", "K'k"), ('Qizil', 'Qizil'), ('Kulrang', 'Kulrang'), ('Jigarrang', 'Jigarrang'), ('Bronza', 'Bronza'), ('Xameleon', 'Xameleon'), ('Feruza', 'Feruza'), ("To'q-qizil", "To'q-qizil"), ('Moviy', 'Moviy'), ('Sariq', 'Sariq'), ('Yashil', 'Yashil'), ('Och-binafsha-rang', 'Och-binafsha-rang'), ('Oltin rang', 'Oltin rang'), ("To'q-sariq", "To'q-sariq"), ('Pushti rang', 'Pushti rang'), ('Binafsha rang', 'Binafsha rang'), ("To'q-ko'k", "To'q-ko'k")], max_length=50, verbose_name='Rangi'),
        ),
        migrations.AlterField(
            model_name='avto',
            name='yeyishi',
            field=models.CharField(choices=[('Benzin', 'Benzin'), ('Gaz', 'Gaz'), ('Elektr', 'Elektr'), ('Benzin/Gaz', 'Benzin/Gaz'), ('Dizel', 'Dizel'), ('Gibrid', 'Gibrid')], max_length=50, verbose_name='Yeyishi'),
        ),
        migrations.AddField(
            model_name='avto',
            name='uzatma',
            field=models.CharField(choices=[('Oldi', 'Oldi'), ('Orqa', 'Orqa'), ("To'liq", "To'liq")], default='Oldi', max_length=10),
        ),
        migrations.AddField(
            model_name='avto',
            name='yurgani',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='avto',
            name='kraska_holati',
            field=models.CharField(choices=[('Kraska toza', 'Kraska toza'), ('Kraskasi bor', 'Kraskasi bor'), ('Pyatno bor', 'Pyatno bor'), ("To'liq kraskalangan", "To'liq kraskalangan")], max_length=50, verbose_name='Kraska Holati'),
        ),
        migrations.AlterField(
            model_name='avto',
            name='yili',
            field=models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=5, verbose_name='Yili'),
        ),
        migrations.DeleteModel(
            name='Karobka',
        ),
        migrations.DeleteModel(
            name='Rang',
        ),
        migrations.DeleteModel(
            name='Yeyishi',
        ),
    ]
