# Generated by Django 5.0.1 on 2024-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0005_alter_avto_karobka_alter_avto_rang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avto',
            name='valyuta',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('SAR', 'SAR'), ('CNY', 'CNY')], default='UZS', max_length=5),
        ),
    ]
