# Generated by Django 5.0.1 on 2024-01-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0006_avto_valyuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='avto',
            name='viewed_list',
            field=models.IntegerField(default=0),
        ),
    ]
