# Generated by Django 5.0.1 on 2024-02-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0007_avto_viewed_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viloyat',
            name='davlat',
        ),
        migrations.RemoveField(
            model_name='shahar',
            name='viloyat',
        ),
        migrations.RemoveField(
            model_name='avto',
            name='shahar',
        ),
        migrations.AddField(
            model_name='avto',
            name='manzil',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='avto',
            name='viloyat',
            field=models.CharField(choices=[('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Fargona', 'Fargʻona'), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ('Qoraqalpog', 'Qoraqalpogʻiston Respublikasi'), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Toshkent', 'Toshkent')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Davlat',
        ),
        migrations.DeleteModel(
            name='Viloyat',
        ),
        migrations.DeleteModel(
            name='Shahar',
        ),
    ]
